### ISSUE TITLE
Função Index

### ISSUE THREAD

**Issue by rafa-acioly** [mvnp/multiple_images_CI#1]
A função index esta tambem buscando os dados no banco após a inserção.
Podemos tirar essa parte e deixar isso por conta de quem for utilizar a classe?

**Comment by mvnp** [comment]
O sistema hoje faz o serviço de upload, cadastro e amostragem das imagens. Qualquer modificação não deve afetar o funcionamento do mesmo. Quem baixar deve conseguir executar imediatamente sem nenhuma implementação adicional. Podemos futuramente aplicar a sua proposta.

Desculpe caso não tenha entendido exatamente o que perguntou :)
